### ISSUE TITLE
hmm_peaks can't detect very extreme peaks

### ISSUE THREAD

**Issue by julianstanley** [miraep8/rendseq#12]
I think `make_peaks()` is working correctly, but this behavior feels weird:

If I make a Z score array of 10,000 Z-scores (normal around mean 0) and then assign a high Z score (e.g. 5) to the middle, `hmm_peaks` detects a peak as expected. If I make it _really_ high, though (e.g. 100), it no longer detects the peak. 

I think this is because of the `peak_center = 10` and `spread = 2` arguments--so, since we expect a Z-score of 10, then a Z-score of 100 is quite unlikely. 

This seems like more of a unintuitive thing about the HMM method and less of a software bug. 

Here's an example:

```python
>>> from rendseq.make_peaks import *
>>> from numpy import array
>>> from numpy.random import normal
>>> z_scores = array([[loc, z] for loc,z in zip(range(1, 10000),
... normal(0, 1, size = (1, 10000))[0])])
>>> for i in [1, 2, 5, 10, 12, 15, 50, 100, 1000]:
...     z_scores[5000, 1] = i
...     print(f'Middle Z score is: {i}')
...     hmm_peaks(z_scores)
...
Middle Z score is: 1
Finding Peaks
Calculating Transition Matrix
Found 0 Peaks
...
Middle Z score is: 2
Finding Peaks
Calculating Transition Matrix
Found 0 Peaks
...
Middle Z score is: 5
Finding Peaks
Calculating Transition Matrix
Found 1 Peaks
...
Middle Z score is: 10
Finding Peaks
Calculating Transition Matrix
Found 1 Peaks
...
Middle Z score is: 50
Finding Peaks
Calculating Transition Matrix
Found 1 Peaks
...
Middle Z score is: 100
Finding Peaks
Calculating Transition Matrix
Found 0 Peaks
...
Middle Z score is: 1000
Finding Peaks
Calculating Transition Matrix
Found 0 Peaks
```

```python
>>> z_scores[5000, 1] = 1e4
>>> hmm_peaks(z_scores, peak_center = 1e4)
Finding Peaks
Calculating Transition Matrix
Found 1 Peaks
```

**Comment by miraep8** [comment]
Hey yep, I think it is actually just a software bug, not necessarily a HMM bug.  Essentially the emission probabilities for both the peak state and the internal state are essentially 0 at these extreme peak values.  In theory the peak state should be slightly more likely, but in reality I think that the code we use to generate the probabilities for both just returns 0, so the HMM has no way to distinguish the two.

In the past I was actually capping the z_scores at 15, which solved this haha.  Then I got rid of that because I didn't like messing with the z scores directly.  What seems like a better solution to me now however is capping all the z scores within `hmm_peaks` to be `peak_center` + `peak_width` or something like that.

**Comment by miraep8** [comment]
Similar to #13 I am going to recommend that we open a new PR for these changes.  I can handle it once I wrap up some of the CI stuff.
