### ISSUE TITLE
p_to_p = 1 doesn't stay in peak state

### ISSUE THREAD

**Issue by julianstanley** [miraep8/rendseq#13]
Similar to #12, I'm not sure if this is a software bug or just me not understanding the HMM implementation.

`hmm_peaks` has a `p_to_p` argument that says it's the probability of moving to peak, given we are currently at a peak.

So I'd think that if `p_to_p = 1`, the moment we see a peak, any subsequent Z-scores should also be peaks. 

Testing that out:

```python
>>> from rendseq.make_peaks import *
>>> from numpy import array
>>> from numpy.random import normal
>>> z_scores = array([[loc, z] for loc,z in zip(range(1, 10000),
... normal(0, 1, size = (1, 10000))[0])])
>>> z_scores[5000, 1] = 5
>>> hmm_peaks(z_scores, p_to_p = 1)
Finding Peaks
Calculating Transition Matrix
Found 2 Peaks
array([[1.000e+00, 1.000e+02],
       [2.000e+00, 1.000e+00],
       [3.000e+00, 1.000e+00],
       ...,
       [9.997e+03, 1.000e+00],
       [9.998e+03, 1.000e+00],
       [9.999e+03, 1.000e+00]])
```

It looks like `p_to_p = 1` just gave me two peaks: one at the beginning of my Z-scores and one in the middle.

Is this the expected behavior?

**Comment by miraep8** [comment]
Hey - so what I think is going on here is that the probabilities used the calculate the likelihood of any particular path probably all reached -Inf/some int overflow issues, and then you end up with weird/unpredictable behavior of the peaks called because the code can no longer differentiate between which path is more likely than another.  Using log probabilities rather than probabilities helped me with this a bit, but my guess is that by forcing p_to_p to be 1, you end up compounding a lot of low probability events (ie all the events where the z score is ~ mean 0 sd 1).  Here is what I recommend:
* To diagnose that this is actually what is going on can actually print/check out the value of the transition matrices. 
* If that is the issue then we should add an error message into the populate_trans_mat function that at least complain if this issue arises in the future. 
* In my mind the preferred behavior for this test case might actually be to throw an error rather than staying in the peak state as it kind of leans into the HMMs probabilistic underpinnings to say - with the parameters you gave me I can't find a good fit, which actually seems like good information to the user.

**Comment by miraep8** [comment]
May I also suggest we open a new PR to address these?  Rather than tacking it on to the already large one

**Comment by miraep8** [comment]
I will work on this now :)  Should have a PR soon
