### ISSUE TITLE
Trilom doesn't allow CI testing on windows

### ISSUE THREAD

**Issue by julianstanley** [miraep8/rendseq#24]
When I add multiple OSx to the github actions job, it fails on the trilom step on Windows: https://github.com/julianstanley/rendseq/actions/runs/2163972249

This is a known issue in trilom that someone fixed and opened a pull request for ~10 months ago : https://github.com/trilom/file-changes-action/pull/124

But it hasn't been merged. To me, trilom looks like it isn't being actively maintained. 

So I think, if we want CI tests on windows, we'll have to use something other than trilom

**Comment by miraep8** [comment]
In fact we could actually get away from using Trilom at all, my only plan was to use it for the style checks so that as the repo grows/more and more files each user is only responsible for linting the files they touched/changed - however one would only expect linting to break for the other files if for some reason we changed the pre-commit in the future. - Arguably whoever made such a decision might then be responsible for re-formatting all the files to guarantee others don't have this issue?   But - not really mission critical to do this check and we could get away with Trilom all together!  In truth this is another idea I borrowed from open source example workflows. :) 

To me - it seems like whoever made Trilom is only interested in it running on Ubuntu?  You can kind of see [that assumption](https://github.com/trilom/file-changes-action) built in in all their use cases. 

At the end of the day I was planning on running all pytests anytime a change is made, so wouldn't be using Trilom or similar to run the test cases you wrote! :) And will be running them on all OS's! And probably the latest 3 versions of python? 

Cheers, thanks for catching this!

**Comment by julianstanley** [comment]
Closed by #26
