### ISSUE TITLE
Lets Squash our merges?

### ISSUE THREAD

**Issue by miraep8** [miraep8/rendseq#34]
Hey all,

Just took a look at our code history and its already pretty messy!  Especially with the CI in place now I imagine this might be the case going forward as well too (ie lots of commits of the nature - fixing linting... or what have you!).  Given that - may I suggest that we switch over to squashing all merges before commiting?  I haven't been doing this either - but just realized it might be a good idea! 

Think this change will make it easier for us to actually make use of the version control powers of git! :)

**Comment by miraep8** [comment]
There is a chance I might also try to clean up what we have already if it isn't too much work!  The plan is to do this in such a way so as not to interfere with ownership over pull requests already made though!

**Comment by julianstanley** [comment]
Sure!

I've heard that there are kind of three schools of thought:

- Don't mess with commits
The idea here is that history--including quick mess ups and typo fixes--are important to document. 

- Squash each pull
Since each pull should be one fix, you only need one commit each

- A mix of the two
I think this is where most folks fall. You don't squash everything, but you package each pull into one or a handful of commits. Because some steps are still helpful. 

I'm down with any--I'm not sure if rebasing already-merged stuff is super straightforward, but if you're willing to figure it out, I don't have any problem with that. 

My thought is that so far we haven't done much to the original repo, so no need to rewrite anything, but doing option (3) seems reasonable to me, just a couple minutes of extra work per pull.

**Comment by julianstanley** [comment]
Oh, and the first two answers here may be helpful: https://stackoverflow.com/questions/6248231/git-rebase-after-previous-git-merge

**Comment by miraep8** [comment]
Yea - I personally like option (2), though could see that if there was a really large pull request with several moving parts it could be worth preserving several commits within that branch!  I will look into the rebasing thing this evening! If its not too much trouble will try it out!

**Comment by miraep8** [comment]
Think its all resolved now, so will be closing this issue, Feel free to reopen if we have any issues though.
