### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by julianstanley** [miraep8/rendseq#5]
Once we have tests setup (depends on #2) we should considering setting up travis-ci to continuously build the tests.

**Comment by miraep8** [comment]
I actually did consider this!  My concern is that I think you actually have to pay for compute for a lot of continuous integration services (at least by my understanding of it!)  While I am sure this is something we could set up - in the short term I was hoping we could just have people pytest (and pylint) their code locally before going we set up a lab account for AWS or Azure or something :)  Maybe this is something we can revisit though in a few weeks/months when we have a better sense of how often people are committing to the repo/we can chat with Gene and see if he is on board?

**Comment by julianstanley** [comment]
Travis and codecov are free

e.g. I have it set-up in my personal packages, like [here](https://github.com/julianstanley/gfpopgui)

It's super straightforward. For a python package, I'll just follow what we did with [edgePy](https://github.com/r-bioinformatics/edgePy).

**Comment by miraep8** [comment]
Great!  I actually was unaware of this free service.  In that case I am all for implementing it!   Thanks for sharing, I think that would be a great addition to the tests you are already implementing.

**Comment by miraep8** [comment]
If its ok with you actually, I might take a stab at setting up a CI over the next few days as well.  Will just set up an automatic check for code style, and once we have some test cases those can be integrated as well! :)

**Comment by miraep8** [comment]
Oo, actually I know you had suggested using travis - but I am leaning towards trying out Github Actions!  I just realized that they are also free for open source projects!! (so many free services!  exciting!).  And it seems like they have an even better direct integration into Github (which perhaps shouldn't be surprising).  (I believe it is also what another open source project I have been working on uses).  Just wanted to check with you first - since you had suggested Travis, would you also be on board with giving Github Actions a try?

**Comment by miraep8** [comment]
Partially resolved by #16 But need to incorporate tests from #14
